### ISSUE TITLE
fly swatter not counting when you get it as a drop

### ISSUE THREAD

**Issue by rethinkingrn** [Antonio32A/SlayerUtilities#1]
![image](https://user-images.githubusercontent.com/48839277/78075754-f8b33880-7359-11ea-99dc-2003bcb50c46.png)
^^ fly swatter drop
![image](https://user-images.githubusercontent.com/48839277/78075778-04066400-735a-11ea-9b0f-7360c2877e6e.png)
fly swatter count is still 0

plz fix

**Comment by marti157** [comment]
Can't reproduce the issue, the tracker code looks fine for this drop.
Please enable your auto-console on error in /ct settings, so that if it happens again we can get some info about the error, if there is one.
